name: coconut_design_system
description: "The Coconut Design System For Coconut Vault/Wallet. Anyone who wants to use this design system is free to do so."
version: 0.7.4
homepage: "https://www.noncelab.com"
repository: "https://github.com/noncelab/coconut_design_system"

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  flutter_svg: ^2.0.10+1
  lottie: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/svg/arrow-back.svg
    - assets/svg/close.svg
    - assets/svg/checkbox.svg
    - assets/svg/checkbox_selected.svg
    - assets/svg/pulldown_check.svg
    - assets/svg/pulldown_close.svg
    - assets/svg/pulldown_open.svg
    - assets/svg/stepper_minus.svg
    - assets/svg/stepper_plus.svg
    - assets/svg/tooltip/error.svg
    - assets/svg/tooltip/info.svg
    - assets/svg/tooltip/normal.svg
    - assets/svg/tooltip/success.svg
    - assets/svg/tooltip/warning.svg
    - assets/svg/info_circle.svg
    - assets/svg/triangle_warning.svg
    - assets/lottie/loading_dark.json
    - assets/lottie/loading_light.json

  fonts:
    - family: SpaceGrotesk
      fonts:
        - asset: assets/fonts/SpaceGrotesk-Bold.ttf
          weight: 700
        - asset: assets/fonts/SpaceGrotesk-Regular.ttf
          weight: 400
        - asset: assets/fonts/SpaceGrotesk-Medium.ttf
          weight: 500
        - asset: assets/fonts/SpaceGrotesk-Light.ttf
          weight: 300
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Bold.ttf
          weight: 700
        - asset: assets/fonts/Pretendard-Regular.ttf
          weight: 400
